baseURL = "https://mafsi.github.io/filip-site/"
languageCode = "ro"
theme = "raditian-free-hugo-theme"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/rad-icons.css"
  [[params.plugins.css]]
  URL = "css/custom.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
  [[params.plugins.js]]
  URL = "js/library/fontfaceobserver.js"


# navigation
[menu]

  [[menu.header]]
  name = "Acasă"
  URL = "/"
  weight = 1

  [[menu.header]]
  name = "Cine sînt"
  URL = "#about"
  weight = 2

  [[menu.header]]
  name = "Experiență"
  URL = "#experience"
  weight = 3

  [[menu.header]]
  name = "Portofoliu"
  URL = "#client-and-work"
  weight = 4

  [[menu.header]]
  name = "Contact"
  URL = "#contact"
  weight = 5


  [[menu.footer]]
  name = "Acasă"
  URL = "/"
  weight = 1

  [[menu.footer]]
  name = "Cine sînt"
  URL = "#about"
  weight = 2

  [[menu.footer]]
  name = "Experiență"
  URL = "#experience"
  weight = 3

  [[menu.footer]]
  name = "Portofoliu"
  URL = "#client-and-work"
  weight = 4

  [[menu.footer]]
  name = "Contact"
  URL = "#contact"
  weight = 5


[params]

  sections = ["showcase", "about", "education", "experience", "client-and-work", "testimonial", "contact", "newsletter"]

  googleTagManagerID = "GTM-000000" # Google Analytics works with Google Tag Manager

  [params.logo]
    text1 = "Filip"
    text2 = "Photography"

  [params.footer]
      copyright = "© 2025 Filip Danilevici Photography. Toate drepturile rezervate."
      [params.footer.radity_logo]
        x = "img/general/design-and-code-radity.png"
        _2x = "img/general/design-and-code-radity@2x.png"
        alt = "Design & Code - Radity"
